# Site settings
# in the templates available like {{ site.myvariable }}.
title: Tedious Website
email: leanlee311@gmail.com
brand: Lingda Li
headline: Inventor, Engineer and Sneakerhead
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lingdali.github.io" # the base hostname & protocol for your site
copyright: Lingda Li's Personal Website. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: leanlee311@gmail.com
phone: +1-352-999-1123

# Tracking
googleAnalitycsID: UA-83933844-1

